config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, :controllers => {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
  }
  devise_for :clients, controllers: {
    registrations: "clients/registrations",
    sessions: "clients/sessions",
    confirmations: "clients/confirmations",
    mailer: "clients/mailer",
    passwords: "clients/passwords",
    shared: "clients/shared",
    unlocks: "clients/unlocks",
  }
  scope module: :clients do
    root 'products#top'
    # 商品
    resources :products, only: %i(show index)
    get 'genres/:id/genre_products' => 'products#genre_products'
    # 注文
    post "orders/pre_create" => "orders#pre_create"
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/after_order" => "orders#after_order"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "clients/withdrawal" => "clients#withdrawal"
    patch "clients/withdrawal" => "clients#withdrawal"
    resources :clients, only: [:show, :edit, :update, :destroy]
    # カート
    resources :inside_carts, only: [:create, :index, :update, :destroy]
    delete 'inside_carts' => 'inside_carts#destroy_all'
    # 登録先住所
    resources :shipping_addresses, only: %i(new create edit update destroy)
  end
  namespace :admins do
    root 'orders#top'
    # 商品
    resources :products, only: %i(new show create edit index update)
    # 注文
    get "orders/top" => "orders#top"
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/product_orders_status" => "orders#product_orders_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: %i(create index update edit)
    # カート
    resources :inside_carts, only: [:update]
    # 会員
    resources :clients, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'seach' => 'seaches#seach'
  end
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :product_orders, dependent: :destroy
  belongs_to :client

  enum payment: {
    "クレジットカード" => 0,
    "銀行振込" => 1,
  }
  enum order_status: {
    "入金待ち" => 0,
    "入金確認" => 1,
    "製作中" => 2,
    "発送準備中" => 3,
    "発送済み" => 4,
  }
end

app/controllers/admins/clients_controller.rb
class Admins::ClientsController < ApplicationController
   before_action :authenticate_admin!
  def show
    @client = Client.with_deleted.find(params[:id])
  end

  def index
    @clients = Client.with_deleted.page(params[:page]).per(10)
  end

  def edit
    @client = Client.with_deleted.find(params[:id])
  end

  def update
    @client = Client.with_deleted.find(params[:id])
    if @client.update(client_params)
      flash[:success] = '個人情報を編集しました'
      redirect_to admins_client_path(@client)
    else
      flash[:danger] = '個人情報の編集に失敗しました'
      render :edit
    end
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :postal_code, :street_address, :deleted_at)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
 before_action :authenticate_admin!

  def top
    from = Time.current.beginning_of_day
    to = Time.current.end_of_day
    @today_orders = Order.where(created_at: from..to)
  end

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @product_orders = @order.product_orders.all
    @sum = 0
    @subtotals = @product_orders.map { |product_order| product_order.once_price * product_order.quantity }
    @sum = @subtotals.sum
  end

  def order_status_update
    @order = Order.find(params[:order][:id])
    if @order.update(params_int(order_params))
      flash[:success] = "注文ステータスを更新しました"
      order_status_is_deposited?(@order)
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "注文ステータスの更新に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def product_orders_status_update
    @product_order = ProductOrder.find(params[:product_order][:id])
    if @product_order.update(params_int(product_order_params))
      flash[:info] = "製作ステータスを更新しました"
      product_order_status_is_in_production?(@product_order)
      @order = Order.find_by(id: params[:product_order][:order_id])
      product_order_status_is_production_complete?(@order)
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "製作ステータスの更新に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

  def product_order_params
    params.require(:product_order).permit(:product_order_status, :id)
  end


  def integer_string?(str)
    Integer(str)
    true
  rescue ArgumentError
    false
  end

  def params_int(order_params)
    order_params.each do |key, value|
      if integer_string?(value)
        order_params[key] = value.to_i
      end
    end
  end


  def order_status_is_deposited?(order)
    if order.order_status_before_type_cast == 1
      order.product_orders.each do |p|
        p.update(product_order_status: 1)
      end
      flash[:info] = "製作ステータスが「製作待ち」に更新されました"
    end
  end


  def product_order_status_is_production_complete?(order)
    if  order.product_orders.all? do |p|
          p.product_order_status_before_type_cast == 3
        end
      order.update(order_status: 3)
      flash[:success] = "注文ステータスが「発送準備中」に更新されました"
    end
  end


  def product_order_status_is_in_production?(product_order)
    if product_order.product_order_status_before_type_cast == 2
      product_order.order.update(order_status: 2)
      flash[:success] = "注文ステータスが「製作中」に更新されました"
    end
  end
end

app/controllers/clients/clients_controller.rb
class Clients::ClientsController < ApplicationController
  before_action :authenticate_client!

  def show
    @client = current_client
  end

  def withdrawal
    @client = current_client
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:success] = "個人情報を編集しました"
      redirect_to client_path(current_client.id)
    else
      flash[:danger] = '個人情報の編集に失敗しました'
      render :edit
    end
  end

  def destroy
    client = Client.find(params[:id])
    client.destroy
    flash[:success] = "アカウントを削除しました"
    redirect_to root_path
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :postal_code, :street_address)
  end
end

app/controllers/clients/confirmations_controller.rb
# frozen_string_literal: true

class Clients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/clients/inside_carts_controller.rb
class Clients::InsideCartsController < ApplicationController
before_action :authenticate_client!
   def create
    @inside_carts = current_client.inside_carts.all
    if inside_carts_params[:quantity] != ""
      if @inside_carts.any? { |inside_cart| inside_cart.product_id == params[:inside_cart][:id].to_i }
        @inside_cart_already = InsideCart.find_by(product_id: params[:inside_cart][:id].to_i)
        @inside_cart_already.quantity += params[:inside_cart][:quantity].to_i
        @inside_cart_already.save
        flash[:success] = "カートに商品を入れました"
        redirect_to inside_carts_path
      else
        @inside_cart = InsideCart.new(
          quantity: params[:inside_cart][:quantity].to_i,
          product_id: params[:inside_cart][:id].to_i,
          client_id: current_client.id
        )
        @inside_cart.save
        flash[:success] = "カートに商品を入れました"
        redirect_to inside_carts_path
      end
    else
      flash[:danger] = "個数を入力してください"
      redirect_back(fallback_location: root_path)
    end
   end

  def index
    @inside_carts = current_client.inside_carts.all
    @sum = 0
    @inside_carts.each do |inside_cart|
      @subtotal = (Product.find(inside_cart.product_id).price * 1.1 * inside_cart.quantity).to_i
      @sum += @subtotal
    end
  end

  def update
    @inside_cart = InsideCart.find(params[:id])
    @inside_cart.quantity = params[:inside_cart][:id]
    @inside_cart.update(inside_carts_params)
    flash[:success] = '個数を変更しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    inside_carts = InsideCart.find_by(id: params[:id], client_id: current_client.id)
    inside_carts.destroy
    flash[:danger] = "カートから削除しました"
    redirect_to inside_carts_path
  end

  def destroy_all
    current_client.inside_carts.destroy_all
    flash[:danger] = "カートが空です"
    redirect_to inside_carts_path
  end

  private

  def inside_carts_params
    params.require(:inside_cart).permit(:quantity, :product_id)
  end
end

app/controllers/clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/clients/orders_controller.rb
class Clients::OrdersController < ApplicationController
 before_action :authenticate_client!
  def new
    @order = Order.new
    @orders = current_client.orders.all
    @client = Client.find(current_client.id)
    @shipping_addresses = @client.shipping_addresses
  end

  def pre_create
    @client = Client.find(current_client.id)
    if order_params[:payment].nil?
      flash[:danger] = "支払い方法を入力してください"
      redirect_back(fallback_location: root_path)
    else
      if params[:selected_address] == "radio1"
        session[:payment] = order_params[:payment]
        session[:postal_code] = @client.postal_code
        session[:street_address] = @client.street_address
        session[:receive_name] = @client.first_name + @client.last_name
        redirect_to orders_confirm_order_path
      elsif params[:selected_address] == "radio2"
        session[:payment] = order_params[:payment]
        if params[:regestrated_address][:regestrated_address] == ""
          flash[:danger] = "登録済み住所を選択してください"
          redirect_back(fallback_location: root_path)
        else
          @selected_shipping_address = @client.shipping_addresses.find(params[:regestrated_address][:regestrated_address])
          session[:postal_code] = @selected_shipping_address.postal_code
          session[:street_address] = @selected_shipping_address.street_address
          session[:receive_name] = @selected_shipping_address.receive_name
          redirect_to orders_confirm_order_path
        end
      elsif params[:selected_address] == "radio3"
        session[:payment] = order_params[:payment]
        session[:postal_code] = order_params[:postal_code]
        session[:street_address] = order_params[:street_address]
        session[:receive_name] = order_params[:receive_name]
        @shipping_address = @client.shipping_addresses.build
        @shipping_address.postal_code = order_params[:postal_code]
        @shipping_address.street_address = order_params[:street_address]
        @shipping_address.receive_name = order_params[:receive_name]
        if @shipping_address.save
          flash[:success] = "新しいお届け先が保存されました"
          redirect_to orders_confirm_order_path
        else
          flash[:danger] = "新しいお届け先の情報を正しく入力してください"
          redirect_back(fallback_location: root_path)
        end
      else
        flash[:danger] = "必要情報を入力してください"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def confirm_order
    @inside_carts = current_client.inside_carts.all
    @order = Order.new(
      payment: session[:payment].to_i,
      receive_name: session[:receive_name],
      postal_code: session[:postal_code],
      street_address: session[:street_address],
      postage: 800
    )
    @sum = 0
    @subtotals = @inside_carts.map { |inside_cart| (Product.find(inside_cart.product_id).price * 1.1 * inside_cart.quantity).to_i }
    @sum = @subtotals.sum
    session[:sum] = @sum
  end

  def create
    @order = Order.new(
      payment: session[:payment].to_i,
      receive_name: session[:receive_name],
      postal_code: session[:postal_code],
      street_address: session[:street_address],
      postage: 800,
      order_status: 0,
      client_id: current_client.id
    )
    @order.total_price = session[:sum] + @order.postage
    if @order.client.inside_carts.count >= 1
      @order.save
      @order.client.inside_carts.each do |i|
        @product_order = @order.product_orders.build
        @product_order.order_id = @order.id
        @product_order.product_order_status = 0
        @product_order.product_id = i.product_id
        @product_order.quantity = (i.quantity * 1.1).to_i
        @product_order.once_price = (i.product.price * 1.1).to_i
        @product_order.save
      end

      @order.client.inside_carts.destroy_all
      session[:payment].clear
      session[:receive_name].clear
      session[:postal_code].clear
      session[:street_address].clear
      session.delete(:sum)
      redirect_to orders_after_order_path
    else
      flash[:danger] = "注文確定に失敗しました.   カートが空でないか確認してください"
      redirect_back(fallback_location: root_path)
    end
  end

  def after_order; end

  def index
    @orders = current_client.orders.all
  end

  def show
    @order = Order.find(params[:id])
    @product_orders = @order.product_orders.all
    @sum = 0
    @subtotals = @product_orders.map { |product_order| product_order.once_price * product_order.quantity }
    @sum = @subtotals.sum
  end

  private

  def order_params
    params.require(:order).permit(:payment, :receive_name, :postal_code, :street_address)
  end
end

app/controllers/clients/passwords_controller.rb
# frozen_string_literal: true

class Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/clients/products_controller.rb
class Clients::ProductsController < ApplicationController
 before_action :ensure_enabled_product, only: [:show, :update]

  def index
    @genres = Genre.where(is_enabled: true)
    if params[:genre_id].nil?
      @products_all = Product.joins(:genre).where(genres: { is_enabled: true }).where(is_enabled: true)
      @products = @products_all.page(params[:page]).reverse_order
      @index = "商品"
    else
      @products_all = Product.joins(:genre).where(genres: { is_enabled: true, id: params[:genre_id] }).where(is_enabled: true)
      @products = @products_all.page(params[:page]).reverse_order
      @index = Genre.find( params[:genre_id]).name
    end
  end

  def show
    @product = Product.find(params[:id])
    @inside_cart = InsideCart.new
    @genres = Genre.where(is_enabled: true)
  end

  def top
    @products = Product.joins(:genre).where(genres: { is_enabled: true }).where(is_enabled: true).order("RANDOM()").limit(6)
    @genres = Genre.where(is_enabled: true)
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :explanation, :image_id, :is_enabled, :genre_id)
  end

  def ensure_enabled_product
    products = Product.joins(:genre).where(genres: { is_enabled: true }).where(is_enabled: true)
    unless products.any? { |p| p == Product.find(params[:id]) }
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/clients/sessions_controller.rb
# frozen_string_literal: true

class Clients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admins/clients_helper.rb
module Admins::ClientsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/clients/clients_helper.rb
module Clients::ClientsHelper
end

app/helpers/clients/inside_carts_helper.rb
module Clients::InsideCartsHelper
end

app/helpers/clients/orders_helper.rb
module Clients::OrdersHelper
end

app/views/clients/orders/after_order.html.erb
<div class="row login-row" >
    <div class="col-xs-offset-5" style="margin-top: 20vh; margin-bottom: 20vh;">
      ご購入ありがとうございました！
    </div>
</div>

app/views/clients/orders/confirm_order.html.erb
<div class="row login-row">
      <h2>注文情報確認</h2>
      <div class="col-xs-8"  style="margin-top: 50px;">
        <table class="table table-bordered">
          <thead>
            <tr class="table-head" style="background-color:#F5F5F5;">
              <th scope="col">商品名</th>
              <th scope="col">単価（税込）</th>
              <th scope="col">数量</th>
              <th scope="col">小計</th>
            </tr>
          </thead>
          <tbody>
            <% @inside_carts.each do |inside_cart| %>
              <tr>
                <td><%= inside_cart.product.name %></td>
                <td><%= (inside_cart.product.price * 1.1).to_i%></td>
                <td><%= inside_cart.quantity %></td>
                <td><%= (Product.find(inside_cart.product_id).price * 1.1 * inside_cart.quantity).to_i  %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <table class="table" style="margin-top: 50px;">
          <tbody>
            <tr>
              <th scope="row">支払い方法</th>
              <td><%= @order.payment %></td>
            </tr>
            <tr>
              <th scope="row">お届け先</th>
              <td>
                <p><%= @order.postal_code %>&emsp;<%= @order.street_address %></p>
                <p><%= @order.receive_name %></p>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="col-xs-4" style="margin-top: 50px;">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <td class="active">送料</td>
              <td><%= @order.postage %></td>
            </tr>
            <tr>
              <td class="active">商品合計</td>
              <td><%= @sum %></td>
            </tr>
            <tr>
              <td class="active">請求合計</td>
              <td><%= @sum + @order.postage %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-offset-5">
        <%= form_with(model: @order, url:orders_path, method: :post, local: true) do |f| %>
              <%= f.submit "注文を確定する",class:"btn btn-primary col-xs-12" %>
        <% end %>
      </div>
    </div>

app/views/clients/orders/index.html.erb
<div class="row login-row">
      <h2>注文履歴一覧</h2>
      <div class="col-xs-10 col-xs-offset-1"style="margin-top: 50px;">
        <table class="table table-bordered">
          <thead>
            <tr class="table-head" style="background-color:#F5F5F5;">
              <th scope="col">注文日</th>
              <th scope="col">配送先</th>
              <th scope="col">注文商品</th>
              <th scope="col">支払金額</th>
              <th scope="col">ステータス</th>
              <th scope="col">注文詳細</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
                <tr>
                  <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                  <td>
                    <p><%= order.postal_code %>&emsp;<%= order.street_address %></p>
                    <p><%= order.receive_name %></p>
                  </td>
                  <td>
                  <% order.product_orders.all.each do |p| %>
                    <p><%= p.product.name %></p>
                  <%end %>
                  </td>
                  <td><%= order.total_price %>円</td>
                  <td><%= order.order_status %></td>
                  <td>
                  <%= link_to "表示する", order, class: 'btn btn-primary' %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>

app/views/clients/orders/new.html.erb
<div class="row login-row">
  <h2>注文情報入力</h2>
  <div class="col-xs-12" style="margin-top: 50px;">
   <%= form_with(model: @order, url: orders_pre_create_path, method: :post, local: true) do |f| %>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">支払い方法</th>
            <td>
              <div class="radio">
                <%= f.radio_button :payment, 0 %>
                <label class="payment-label"> クレジットカード</label>
                <%= f.radio_button :payment, 1 %>
                <label class="payment-label">銀行振込</label>
              </div>
            </td>
          </tr>
          <tr>
            <th scope="row">お届け先</th>
            <td>
              <div class="radio">
                <%= radio_button_tag(:selected_address, :radio1) %>
                <%= label_tag(:selected_address, "ご自身の住所") %>
                <p>&emsp;<%= @client.postal_code %><%= @client.street_address %></p>
                <p>&emsp;<%= @client.first_name %><%= @client.last_name %></p>
              </div>
              <div class="radio">
                <%= radio_button_tag(:selected_address, :radio2) %>
                <%= label_tag(:selected_address, "登録済住所から選択") %>
                <p>&emsp;
                <%= collection_select(:regestrated_address, :regestrated_address, current_client.shipping_addresses.all, :id, :full_address, prompt: "住所を選択してください" )%>
                </p>
              </div>
              <div class="radio">
                <%= radio_button_tag(:selected_address, :radio3) %>
                <%= label_tag(:selected_address, "新しいお届け先") %>
                 <div class="field">
                  <label class="postal-code-label">郵便番号(ハイフンなし)</label>
                  <%= f.text_field :postal_code, autofocus: true, class:""%>
                </div>
                <div class="field">
                  <label class="address-label">住所</label>
                  <%= f.text_field :street_address, autofocus: true, class:"", size:"60*60"%>
                </div>
                 <div class="field">
                <label class="address-label">宛名</label>
                 <%= f.text_field :receive_name, autofocus: true, class:"", size:"30*30" %>
                </div>
             </div>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="col-xs-offset-5">
        <%= f.submit "確認画面へ進む",class:"btn btn-primary col-xs-3 " %>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/orders/show.html.erb
<div class="row login-row">
      <h2>注文履歴詳細</h2>
      <div class="col-xs-8"  style="margin-top: 50px;">
        <h4>注文情報</h4>
        <table class="table table-bordered">
          <tbody>
            <tr>
              <td class="active">注文日</td>
              <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
            <tr>
              <td class="active">配送先</td>
              <td>
                 <p><%= @order.postal_code %>&emsp;<%= @order.street_address %></p>
                    <p><%= @order.receive_name %></p>
              </td>
            </tr>
            <tr>
              <td class="active">支払い方法</td>
              <td><%= @order.payment %></td>
            </tr>
            <tr>
              <td class="active">ステータス</td>
              <td><%= @order.order_status %></td>
            </tr>
          </tbody>
        </table>

        <h4 style="margin-top: 50px;">注文内容</h4>
        <table class="table table-bordered">
          <thead>
            <tr class="table-head" style="background-color:#F5F5F5;">
              <th scope="col">商品</th>
              <th scope="col">単価（税込）</th>
              <th scope="col">個数</th>
              <th scope="col">小計</th>
            </tr>
          </thead>
          <tbody>
            <% @product_orders.each do |product_order| %>
                <tr>
                  <td><%= product_order.product.name %></td>
                  <td><%= product_order.once_price %></td>
                  <td><%= product_order.quantity %></td>
                  <td><%= product_order.once_price * product_order.quantity %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-xs-4" style="margin-top: 50px;">
        <h4>請求情報</h4>
        <table class="table table-bordered">
          <tbody>
            <tr>
              <td class="active">商品合計</td>
              <td><%= @sum %></td>
            </tr>
            <tr>
              <td class="active">配送料</td>
              <td><%= @order.postage %></td>
            </tr>
            <tr>
              <td class="active">ご請求額</td>
              <td><%= @order.total_price %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>