config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, :controllers => {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
  }
  devise_for :clients, controllers: {
    registrations: "clients/registrations",
    sessions: "clients/sessions",
    confirmations: "clients/confirmations",
    mailer: "clients/mailer",
    passwords: "clients/passwords",
    shared: "clients/shared",
    unlocks: "clients/unlocks",
  }
  scope module: :clients do
    root 'products#top'
    # 商品
    resources :products, only: %i(show index)
    get 'genres/:id/genre_products' => 'products#genre_products'
    # 注文
    post "orders/pre_create" => "orders#pre_create"
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/after_order" => "orders#after_order"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "clients/withdrawal" => "clients#withdrawal"
    patch "clients/withdrawal" => "clients#withdrawal"
    resources :clients, only: [:show, :edit, :update, :destroy]
    # カート
    resources :inside_carts, only: [:create, :index, :update, :destroy]
    delete 'inside_carts' => 'inside_carts#destroy_all'
    # 登録先住所
    resources :shipping_addresses, only: %i(new create edit update destroy)
  end
  namespace :admins do
    root 'orders#top'
    # 商品
    resources :products, only: %i(new show create edit index update)
    # 注文
    get "orders/top" => "orders#top"
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/product_orders_status" => "orders#product_orders_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: %i(create index update edit)
    # カート
    resources :inside_carts, only: [:update]
    # 会員
    resources :clients, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'seach' => 'seaches#seach'
  end
end

app/controllers/admins/clients_controller.rb
class Admins::ClientsController < ApplicationController
   before_action :authenticate_admin!
  def show
    @client = Client.with_deleted.find(params[:id])
  end

  def index
    @clients = Client.with_deleted.page(params[:page]).per(10)
  end

  def edit
    @client = Client.with_deleted.find(params[:id])
  end

  def update
    @client = Client.with_deleted.find(params[:id])
    if @client.update(client_params)
      flash[:success] = '個人情報を編集しました'
      redirect_to admins_client_path(@client)
    else
      flash[:danger] = '個人情報の編集に失敗しました'
      render :edit
    end
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :postal_code, :street_address, :deleted_at)
  end
end

app/controllers/clients/clients_controller.rb
class Clients::ClientsController < ApplicationController
  before_action :authenticate_client!

  def show
    @client = current_client
  end

  def withdrawal
    @client = current_client
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:success] = "個人情報を編集しました"
      redirect_to client_path(current_client.id)
    else
      flash[:danger] = '個人情報の編集に失敗しました'
      render :edit
    end
  end

  def destroy
    client = Client.find(params[:id])
    client.destroy
    flash[:success] = "アカウントを削除しました"
    redirect_to root_path
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :postal_code, :street_address)
  end
end

app/controllers/clients/confirmations_controller.rb
# frozen_string_literal: true

class Clients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/clients/inside_carts_controller.rb
class Clients::InsideCartsController < ApplicationController
before_action :authenticate_client!
   def create
    @inside_carts = current_client.inside_carts.all
    if inside_carts_params[:quantity] != ""
      if @inside_carts.any? { |inside_cart| inside_cart.product_id == params[:inside_cart][:id].to_i }
        @inside_cart_already = InsideCart.find_by(product_id: params[:inside_cart][:id].to_i)
        @inside_cart_already.quantity += params[:inside_cart][:quantity].to_i
        @inside_cart_already.save
        flash[:success] = "カートに商品を入れました"
        redirect_to inside_carts_path
      else
        @inside_cart = InsideCart.new(
          quantity: params[:inside_cart][:quantity].to_i,
          product_id: params[:inside_cart][:id].to_i,
          client_id: current_client.id
        )
        @inside_cart.save
        flash[:success] = "カートに商品を入れました"
        redirect_to inside_carts_path
      end
    else
      flash[:danger] = "個数を入力してください"
      redirect_back(fallback_location: root_path)
    end
   end

  def index
    @inside_carts = current_client.inside_carts.all
    @sum = 0
    @inside_carts.each do |inside_cart|
      @subtotal = (Product.find(inside_cart.product_id).price * 1.1 * inside_cart.quantity).to_i
      @sum += @subtotal
    end
  end

  def update
    @inside_cart = InsideCart.find(params[:id])
    @inside_cart.quantity = params[:inside_cart][:id]
    @inside_cart.update(inside_carts_params)
    flash[:success] = '個数を変更しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    inside_carts = InsideCart.find_by(id: params[:id], client_id: current_client.id)
    inside_carts.destroy
    flash[:danger] = "カートから削除しました"
    redirect_to inside_carts_path
  end

  def destroy_all
    current_client.inside_carts.destroy_all
    flash[:danger] = "カートが空です"
    redirect_to inside_carts_path
  end

  private

  def inside_carts_params
    params.require(:inside_cart).permit(:quantity, :product_id)
  end
end

app/controllers/clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/clients/orders_controller.rb
class Clients::OrdersController < ApplicationController
 before_action :authenticate_client!
  def new
    @order = Order.new
    @orders = current_client.orders.all
    @client = Client.find(current_client.id)
    @shipping_addresses = @client.shipping_addresses
  end

  def pre_create
    @client = Client.find(current_client.id)
    if order_params[:payment].nil?
      flash[:danger] = "支払い方法を入力してください"
      redirect_back(fallback_location: root_path)
    else
      if params[:selected_address] == "radio1"
        session[:payment] = order_params[:payment]
        session[:postal_code] = @client.postal_code
        session[:street_address] = @client.street_address
        session[:receive_name] = @client.first_name + @client.last_name
        redirect_to orders_confirm_order_path
      elsif params[:selected_address] == "radio2"
        session[:payment] = order_params[:payment]
        if params[:regestrated_address][:regestrated_address] == ""
          flash[:danger] = "登録済み住所を選択してください"
          redirect_back(fallback_location: root_path)
        else
          @selected_shipping_address = @client.shipping_addresses.find(params[:regestrated_address][:regestrated_address])
          session[:postal_code] = @selected_shipping_address.postal_code
          session[:street_address] = @selected_shipping_address.street_address
          session[:receive_name] = @selected_shipping_address.receive_name
          redirect_to orders_confirm_order_path
        end
      elsif params[:selected_address] == "radio3"
        session[:payment] = order_params[:payment]
        session[:postal_code] = order_params[:postal_code]
        session[:street_address] = order_params[:street_address]
        session[:receive_name] = order_params[:receive_name]
        @shipping_address = @client.shipping_addresses.build
        @shipping_address.postal_code = order_params[:postal_code]
        @shipping_address.street_address = order_params[:street_address]
        @shipping_address.receive_name = order_params[:receive_name]
        if @shipping_address.save
          flash[:success] = "新しいお届け先が保存されました"
          redirect_to orders_confirm_order_path
        else
          flash[:danger] = "新しいお届け先の情報を正しく入力してください"
          redirect_back(fallback_location: root_path)
        end
      else
        flash[:danger] = "必要情報を入力してください"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def confirm_order
    @inside_carts = current_client.inside_carts.all
    @order = Order.new(
      payment: session[:payment].to_i,
      receive_name: session[:receive_name],
      postal_code: session[:postal_code],
      street_address: session[:street_address],
      postage: 800
    )
    @sum = 0
    @subtotals = @inside_carts.map { |inside_cart| (Product.find(inside_cart.product_id).price * 1.1 * inside_cart.quantity).to_i }
    @sum = @subtotals.sum
    session[:sum] = @sum
  end

  def create
    @order = Order.new(
      payment: session[:payment].to_i,
      receive_name: session[:receive_name],
      postal_code: session[:postal_code],
      street_address: session[:street_address],
      postage: 800,
      order_status: 0,
      client_id: current_client.id
    )
    @order.total_price = session[:sum] + @order.postage
    if @order.client.inside_carts.count >= 1
      @order.save
      @order.client.inside_carts.each do |i|
        @product_order = @order.product_orders.build
        @product_order.order_id = @order.id
        @product_order.product_order_status = 0
        @product_order.product_id = i.product_id
        @product_order.quantity = (i.quantity * 1.1).to_i
        @product_order.once_price = (i.product.price * 1.1).to_i
        @product_order.save
      end

      @order.client.inside_carts.destroy_all
      session[:payment].clear
      session[:receive_name].clear
      session[:postal_code].clear
      session[:street_address].clear
      session.delete(:sum)
      redirect_to orders_after_order_path
    else
      flash[:danger] = "注文確定に失敗しました.   カートが空でないか確認してください"
      redirect_back(fallback_location: root_path)
    end
  end

  def after_order; end

  def index
    @orders = current_client.orders.all
  end

  def show
    @order = Order.find(params[:id])
    @product_orders = @order.product_orders.all
    @sum = 0
    @subtotals = @product_orders.map { |product_order| product_order.once_price * product_order.quantity }
    @sum = @subtotals.sum
  end

  private

  def order_params
    params.require(:order).permit(:payment, :receive_name, :postal_code, :street_address)
  end
end

app/controllers/clients/passwords_controller.rb
# frozen_string_literal: true

class Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/clients/products_controller.rb
class Clients::ProductsController < ApplicationController
 before_action :ensure_enabled_product, only: [:show, :update]

  def index
    @genres = Genre.where(is_enabled: true)
    if params[:genre_id].nil?
      @products_all = Product.joins(:genre).where(genres: { is_enabled: true }).where(is_enabled: true)
      @products = @products_all.page(params[:page]).reverse_order
      @index = "商品"
    else
      @products_all = Product.joins(:genre).where(genres: { is_enabled: true, id: params[:genre_id] }).where(is_enabled: true)
      @products = @products_all.page(params[:page]).reverse_order
      @index = Genre.find( params[:genre_id]).name
    end
  end

  def show
    @product = Product.find(params[:id])
    @inside_cart = InsideCart.new
    @genres = Genre.where(is_enabled: true)
  end

  def top
    @products = Product.joins(:genre).where(genres: { is_enabled: true }).where(is_enabled: true).order("RANDOM()").limit(6)
    @genres = Genre.where(is_enabled: true)
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :explanation, :image_id, :is_enabled, :genre_id)
  end

  def ensure_enabled_product
    products = Product.joins(:genre).where(genres: { is_enabled: true }).where(is_enabled: true)
    unless products.any? { |p| p == Product.find(params[:id]) }
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/clients/registrations_controller.rb
# frozen_string_literal: true

class Clients::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/clients/sessions_controller.rb
# frozen_string_literal: true

class Clients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/clients/shipping_addresses_controller.rb
class Clients::ShippingAddressesController < ApplicationController
  def new
    @shipping_address = ShippingAddress.new
    @shipping_addresses = ShippingAddress.all
  end

  def edit
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def create
    shipping_address = ShippingAddress.new(shipping_address_params)
    shipping_address.client_id = current_client.id
    if shipping_address.save
      flash[:success] = '配送先を登録しました'
      redirect_to new_shipping_address_path
    else
      flash[:danger] =
        '必要情報を入力してください／ハイフンは使用できません'
      redirect_to new_shipping_address_path
    end
  end

  def update
    shipping_address = ShippingAddress.find(params[:id])
    if shipping_address.update(shipping_address_params)
      flash[:success] = '編集を保存しました'
      redirect_to new_shipping_address_path
    else
      @shipping_address = ShippingAddress.find(params[:id])
      flash[:danger] =
        '必要情報を入力してください／ハイフンは使用できません'
      render "clients/shipping_addresses/edit"
    end
  end

  def destroy
    shipping_address = ShippingAddress.find(params[:id])
    shipping_address.destroy
    flash[:success] = '削除しました'
    redirect_to new_shipping_address_path
  end

  private

  def shipping_address_params
    params.require(:shipping_address).permit(:postal_code, :street_address, :receive_name)
  end
end

app/helpers/admins/clients_helper.rb
module Admins::ClientsHelper
end

app/helpers/clients/clients_helper.rb
module Clients::ClientsHelper
end

app/helpers/clients/inside_carts_helper.rb
module Clients::InsideCartsHelper
end

app/helpers/clients/orders_helper.rb
module Clients::OrdersHelper
end

app/helpers/clients/products_helper.rb
module Clients::ProductsHelper
end

app/helpers/clients/shipping_addresses_helper.rb
module Clients::ShippingAddressesHelper
end

app/views/admins/clients/edit.html.erb
<div class=“row”>
	<div class = "body" style>
		<div class = "container">
			<h2><%= @client.first_name %><%= @client.last_name %>さんの会員情報編集</h2>

				<%= form_for [:admins,@client] do |f| %>
				<div class="field">
	              <%= f.label :会員ID %><br>
	                <%= @client.id %>
	              </div>

				<div class="field">
				    <%= f.label :名前 %><br>
				    <%= f.label :（姓） %>
				    <%= f.text_field :first_name, autofocus: true, autocomplete: "email" %>
				    <%= f.label :（名） %>
				    <%= f.text_field :last_name, autofocus: true, autocomplete: "email" %>
				 </div>

				 <div class="field">
				    <%= f.label :フリガナ %><br />
				    <%= f.label :（セイ） %>
				    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "email" %>
				    <%= f.label :（メイ） %>
				    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "email" %>
				 </div>

				 <div class="field">
				    <%= f.label :郵便番号（ハイフンなし） %><br />
				    <%= f.text_field :postal_code, autofocus: true, autocomplete: "email" %>
				 </div>

				 <div class="field">
				    <%= f.label :住所 %><br />
				    <%= f.text_field :street_address, autofocus: true, autocomplete: "email" %>
				 </div>

				 <div class="field">
				    <%= f.label :電話番号（ハイフンなし） %><br />
				    <%= f.text_field :phone_number, autofocus: true, autocomplete: "email" %>

				 <div class="field">
				    <%= f.label :メールアドレス %><br />
				    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
				 </div>

				 <div class="field">
				    <%= f.label :会員ステータス %><br>
				     <% if @client.deleted_at == nil %>
				    	<label><%= f.radio_button :deleted_at,  {value: ""}, {checked: true} %>有効</label>
				 		<label><%= f.radio_button :deleted_at, value: Time.now %>退会</label>
				 	<% else %>
				 		<label><%= f.radio_button :deleted_at,  value: "" %>有効</label>
				 		<label><%= f.radio_button :deleted_at, {value: Time.now}, {checked: true} %>退会</label>
				 	<% end %>
				 </div>

				    <%= f.submit "編集内容を保存する", class: "btn btn-primary"%>

				 </div>
			<% end %>
		</div>
	</div>
</div>

app/views/admins/clients/index.html.erb
<div class=“row”>
	<h2>会員一覧</h2>

	<table class="table">
	    <thead>
			<tr>
				<th>会員ID</th>
				<th>氏名</th>
				<th>メールアドレス</th>
				<th>ステータス</th>
			</tr>
		</thead>

		<tbody>
			<% @clients.each do |client| %>
				<tr>
					<td><%= client.id %></td>
					<td style>
						<%= link_to client.first_name, admins_client_path(client.id)%>
						<%= link_to client.last_name, admins_client_path(client.id) %>
					</td>
	  				<td> <%= client.email %></td>
					<td><% if client.deleted_at == nil %>
					        有効
					    <% else %>
					        退会
					    <% end %>
					</td>
				</tr>
			<% end %>

			<%= paginate @clients %>
		</tbody>
	</table>
</div>

app/views/admins/clients/show.html.erb
<div class=“row”>
  <div class = "body" style>
  	<div class = "container">
  		<br><br>
        <h2><%= @client.first_name %><%= @client.last_name %>さんの会員情報</h2>

          <table class="table">
            <thead>
              <tr>
                <th scope="col">会員ID</th>
                <td style>
                  <%= @client.id %>&ensp;
                  <% if @client.deleted_at == nil %>
                    有効
                  <% else %>
                    退会
                  <% end %>
                </td>
              </tr>

              <tr>
                <th scope="col">氏名</th>
                <td style><%= @client.first_name %>&ensp;<%= @client.last_name %></td>
              </tr>

              <tr>
                <th scope="col">カナ</th>
                <td style><%= @client.first_name_kana %>&ensp;<%= @client.last_name_kana %></td>
              </tr>

              <tr>
                <th scope="col">郵便番号</th>
                <td style><%= @client.postal_code %></td>
              </tr>

              <tr>
                 <th scope="col">住所</th>
                <td style><%= @client.street_address %></td>
              </tr>

              <tr>
                <th scope="col">電話番号</th>
                <td style><%= @client.phone_number %></td>
              </tr>

              <tr>
                <th scope="col">メールアドレス</th>
                <td style><%= @client.email %></td>
              </tr>
          </thead>
  	</table>

  	 <%= link_to "編集する", edit_admins_client_path, class: "btn btn-primary" %>
  	 <%= link_to "注文履歴一覧を見る", admins_orders_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>