config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, :controllers => {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
  }
  devise_for :clients, controllers: {
    registrations: "clients/registrations",
    sessions: "clients/sessions",
    confirmations: "clients/confirmations",
    mailer: "clients/mailer",
    passwords: "clients/passwords",
    shared: "clients/shared",
    unlocks: "clients/unlocks",
  }
  scope module: :clients do
    root 'products#top'
    # 商品
    resources :products, only: %i(show index)
    get 'genres/:id/genre_products' => 'products#genre_products'
    # 注文
    post "orders/pre_create" => "orders#pre_create"
    get "orders/confirm_order" => "orders#confirm_order"
    get "orders/after_order" => "orders#after_order"
    resources :orders, only: [:new, :show, :create, :index]
    # 会員
    get "clients/withdrawal" => "clients#withdrawal"
    patch "clients/withdrawal" => "clients#withdrawal"
    resources :clients, only: [:show, :edit, :update, :destroy]
    # カート
    resources :inside_carts, only: [:create, :index, :update, :destroy]
    delete 'inside_carts' => 'inside_carts#destroy_all'
    # 登録先住所
    resources :shipping_addresses, only: %i(new create edit update destroy)
  end
  namespace :admins do
    root 'orders#top'
    # 商品
    resources :products, only: %i(new show create edit index update)
    # 注文
    get "orders/top" => "orders#top"
    patch "orders/order_status" => "orders#order_status_update"
    patch "orders/product_orders_status" => "orders#product_orders_status_update"
    resources :orders, only: [:show, :index]
    # ジャンル
    resources :genres, only: %i(create index update edit)
    # カート
    resources :inside_carts, only: [:update]
    # 会員
    resources :clients, only: [:show, :index, :edit, :update, :destroy]
    # 検索
    get 'seach' => 'seaches#seach'
  end
end

app/models/order.rb
class Order < ApplicationRecord
   has_many :product_orders, dependent: :destroy
  belongs_to :client

  enum payment: {
    "クレジットカード" => 0,
    "銀行振込" => 1,
  }
  enum order_status: {
    "入金待ち" => 0,
    "入金確認" => 1,
    "製作中" => 2,
    "発送準備中" => 3,
    "発送済み" => 4,
  }
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
 before_action :authenticate_admin!

  def top
    from = Time.current.beginning_of_day
    to = Time.current.end_of_day
    @today_orders = Order.where(created_at: from..to)
  end

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @product_orders = @order.product_orders.all
    @sum = 0
    @subtotals = @product_orders.map { |product_order| product_order.once_price * product_order.quantity }
    @sum = @subtotals.sum
  end

  def order_status_update
    @order = Order.find(params[:order][:id])
    if @order.update(params_int(order_params))
      flash[:success] = "注文ステータスを更新しました"
      order_status_is_deposited?(@order)
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "注文ステータスの更新に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def product_orders_status_update
    @product_order = ProductOrder.find(params[:product_order][:id])
    if @product_order.update(params_int(product_order_params))
      flash[:info] = "製作ステータスを更新しました"
      product_order_status_is_in_production?(@product_order)
      @order = Order.find_by(id: params[:product_order][:order_id])
      product_order_status_is_production_complete?(@order)
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "製作ステータスの更新に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

  def product_order_params
    params.require(:product_order).permit(:product_order_status, :id)
  end


  def integer_string?(str)
    Integer(str)
    true
  rescue ArgumentError
    false
  end

  def params_int(order_params)
    order_params.each do |key, value|
      if integer_string?(value)
        order_params[key] = value.to_i
      end
    end
  end


  def order_status_is_deposited?(order)
    if order.order_status_before_type_cast == 1
      order.product_orders.each do |p|
        p.update(product_order_status: 1)
      end
      flash[:info] = "製作ステータスが「製作待ち」に更新されました"
    end
  end


  def product_order_status_is_production_complete?(order)
    if  order.product_orders.all? do |p|
          p.product_order_status_before_type_cast == 3
        end
      order.update(order_status: 3)
      flash[:success] = "注文ステータスが「発送準備中」に更新されました"
    end
  end


  def product_order_status_is_in_production?(product_order)
    if product_order.product_order_status_before_type_cast == 2
      product_order.order.update(order_status: 2)
      flash[:success] = "注文ステータスが「製作中」に更新されました"
    end
  end
end

app/controllers/clients/orders_controller.rb
class Clients::OrdersController < ApplicationController
 before_action :authenticate_client!
  def new
    @order = Order.new
    @orders = current_client.orders.all
    @client = Client.find(current_client.id)
    @shipping_addresses = @client.shipping_addresses
  end

  def pre_create
    @client = Client.find(current_client.id)
    if order_params[:payment].nil?
      flash[:danger] = "支払い方法を入力してください"
      redirect_back(fallback_location: root_path)
    else
      if params[:selected_address] == "radio1"
        session[:payment] = order_params[:payment]
        session[:postal_code] = @client.postal_code
        session[:street_address] = @client.street_address
        session[:receive_name] = @client.first_name + @client.last_name
        redirect_to orders_confirm_order_path
      elsif params[:selected_address] == "radio2"
        session[:payment] = order_params[:payment]
        if params[:regestrated_address][:regestrated_address] == ""
          flash[:danger] = "登録済み住所を選択してください"
          redirect_back(fallback_location: root_path)
        else
          @selected_shipping_address = @client.shipping_addresses.find(params[:regestrated_address][:regestrated_address])
          session[:postal_code] = @selected_shipping_address.postal_code
          session[:street_address] = @selected_shipping_address.street_address
          session[:receive_name] = @selected_shipping_address.receive_name
          redirect_to orders_confirm_order_path
        end
      elsif params[:selected_address] == "radio3"
        session[:payment] = order_params[:payment]
        session[:postal_code] = order_params[:postal_code]
        session[:street_address] = order_params[:street_address]
        session[:receive_name] = order_params[:receive_name]
        @shipping_address = @client.shipping_addresses.build
        @shipping_address.postal_code = order_params[:postal_code]
        @shipping_address.street_address = order_params[:street_address]
        @shipping_address.receive_name = order_params[:receive_name]
        if @shipping_address.save
          flash[:success] = "新しいお届け先が保存されました"
          redirect_to orders_confirm_order_path
        else
          flash[:danger] = "新しいお届け先の情報を正しく入力してください"
          redirect_back(fallback_location: root_path)
        end
      else
        flash[:danger] = "必要情報を入力してください"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def confirm_order
    @inside_carts = current_client.inside_carts.all
    @order = Order.new(
      payment: session[:payment].to_i,
      receive_name: session[:receive_name],
      postal_code: session[:postal_code],
      street_address: session[:street_address],
      postage: 800
    )
    @sum = 0
    @subtotals = @inside_carts.map { |inside_cart| (Product.find(inside_cart.product_id).price * 1.1 * inside_cart.quantity).to_i }
    @sum = @subtotals.sum
    session[:sum] = @sum
  end

  def create
    @order = Order.new(
      payment: session[:payment].to_i,
      receive_name: session[:receive_name],
      postal_code: session[:postal_code],
      street_address: session[:street_address],
      postage: 800,
      order_status: 0,
      client_id: current_client.id
    )
    @order.total_price = session[:sum] + @order.postage
    if @order.client.inside_carts.count >= 1
      @order.save
      @order.client.inside_carts.each do |i|
        @product_order = @order.product_orders.build
        @product_order.order_id = @order.id
        @product_order.product_order_status = 0
        @product_order.product_id = i.product_id
        @product_order.quantity = (i.quantity * 1.1).to_i
        @product_order.once_price = (i.product.price * 1.1).to_i
        @product_order.save
      end

      @order.client.inside_carts.destroy_all
      session[:payment].clear
      session[:receive_name].clear
      session[:postal_code].clear
      session[:street_address].clear
      session.delete(:sum)
      redirect_to orders_after_order_path
    else
      flash[:danger] = "注文確定に失敗しました.   カートが空でないか確認してください"
      redirect_back(fallback_location: root_path)
    end
  end

  def after_order; end

  def index
    @orders = current_client.orders.all
  end

  def show
    @order = Order.find(params[:id])
    @product_orders = @order.product_orders.all
    @sum = 0
    @subtotals = @product_orders.map { |product_order| product_order.once_price * product_order.quantity }
    @sum = @subtotals.sum
  end

  private

  def order_params
    params.require(:order).permit(:payment, :receive_name, :postal_code, :street_address)
  end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/clients/orders_helper.rb
module Clients::OrdersHelper
end

app/views/admins/orders/index.html.erb
<div class="row">
<h2>ジャンル一覧・追加</h2>

<%= form_for(@genre, url:'/admins/genres') do |f| %>

	<p>ジャンル</p>
	<%= f.text_field :name %>

	<label><%= f.radio_button :is_enabled, "true" %>有効</label>
	<label><%= f.radio_button :is_enabled, "false" %>無効</label>

	<%= f.submit '追加', class: 'btn btn-primary' %>
<%end%>

<table class="table table-bordere">
	<thead>
		<tr>
			<th>ジャンル</th>
			<th>状態</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<% @genres.each do |genre| %>
			<tr>
				<td><%= genre.name %></td>
				<td>
					<% if genre.is_enabled == true %>
  							有効
					<% else %>
   							無効
 					<% end %>
 				</td>
				<td><%= link_to "編集する", edit_admins_genre_path(genre.id), class: 'btn btn-success' %></td>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/admins/orders/show.html.erb
<div class="row">
  <h2>注文履歴詳細</h2>
  <div style="margin-top: 50px;">
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">購入者</th>
          <td><%=link_to @order.client.first_name + @order.client.last_name , admins_client_path(@order.client.id) %></td>
        </tr>
        <tr>
          <th scope="row">配送先</th>
          <td>
            <p><%= @order.postal_code %><%= @order.street_address %></p>
            <p><%= @order.receive_name %></p>
          </td>
        </tr>
        <tr>
          <th scope="row">支払方法</th>
          <td><%= @order.payment %></td>
        </tr>
        <tr>
          <th scope="row">注文ステータス</th>
          <td>
            <%= form_with(model: @order, url: admins_orders_order_status_path, method: :patch, local: true) do |f| %>
              <%= f.select :order_status, Order.order_statuses.keys.to_a, {} %>
              <%= f.hidden_field :id, :value => @order.id %>
              <%= f.submit "更新",class:"btn btn-primary" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-8"style="margin-top: 50px;">
    <table class="table table-bordered">
      <thead>
        <tr class="table-head" style="background-color:#F5F5F5;">
          <th scope="col">商品名</th>
          <th scope="col">単価（税込）</th>
          <th scope="col">数量</th>
          <th scope="col">小計</th>
          <th scope="col">製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @product_orders.each do |product_order| %>
          <tr>
            <td><%= product_order.product.name %></td>
            <td><%= product_order.once_price %></td>
            <td><%= product_order.quantity %></td>
            <td><%= product_order.once_price * product_order.quantity %>
            </td>
            <td>
               <%= form_with(model: product_order, url: admins_orders_product_orders_status_path, method: :patch, local: true) do |f| %>
                <%= f.select :product_order_status, [["着手不可", 0], ["製作待ち", 1], ["製作中", 2], ["製作完了", 3]] ,selected: product_order.product_order_status_before_type_cast %>
                <%= f.hidden_field :id, :value => product_order.id %>
                <%= f.hidden_field :order_id, :value => @order.id %>
                <%= f.submit "更新",class:"btn btn-primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-xs-4"style="margin-top: 120px;">
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">商品合計</th>
          <td><%= @sum %></td>
        </tr>
        <tr>
          <th scope="row">送料</th>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <th scope="row">請求金額合計</th>
          <td><%= @sum + @order.postage %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/orders/top.html.erb
   <div class="row" >
      <h2>管理者画面</h2>
      <div class="today_order">
        本日の注文件数<span class="today_order_count"><%= @today_orders.count %> 件</span>
      </div>
    </div>
    </div>